# TrajectoryPlannerROS:
#   max_vel_x: 0.18
#   min_vel_x: 0.08
#   max_vel_theta: 1.0
#   min_in_place_vel_theta: -1.0

#   acc_lim_theta: 0.6
#   acc_lim_x: 1.0
#   acc_lim_y: 0.5

#   xy_goal_tolerance: 0.10
#   yaw_goal_tolerance: 0.05

 
#   holonomic_robot: true
#   sim_time: 0.8
#   vx_samples: 18
#   vtheta_samples: 20
#   sim_granularity: 0.05

# controller_frequency: 5.0
# TrajectoryPlannerROS:
#   holonomic_robot: false
#   meter_scoring: true
#   max_vel_x: 0.09
#   min_vel_x: -0.09
  
#   xy_goal_tolerance: 2.0
#   yaw_goal_tolerance: 3.14159

TrajectoryPlannerROS:
  max_vel_x: 0.18
  min_vel_x: 0.08
  max_vel_theta: 1.0
  min_in_place_vel_theta: -1.0

  acc_lim_theta: 0.6
  acc_lim_x: 1.0
  acc_lim_y: 0.5

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.10

 
  holonomic_robot: false
  sim_time: 0.8
  vx_samples: 18
  vtheta_samples: 20
  sim_granularity: 0.05
