# static_map - True if using existing map

# global_costmap:
#   global_frame: map
#   robot_base_frame: base_link
#   update_frequency: 2.0
#   publish_frequency: 2.0
#   transform_tolerance: 0.5
#   static_map: true

# global_costmap: 
#   global_frame: map
#   static_map: true

# global_frame: map
# rolling_window: false
# track_unknown_space: true

# plugins:
#   - {name: static,                  type: "costmap_2d::StaticLayer"}
#   - {name: inflation,               type: "costmap_2d::InflationLayer"}

# static_map - True if using existing map

# global_costmap:
#   global_frame: map
#   robot_base_frame: base_link
#   update_frequency: 5.0
#   publish_frequency: 2.0
#   transform_tolerance: 0.5
#   static_map: true

# global_frame: map
# rolling_window: false
# track_unknown_space: true

# plugins:
#   - {name: static,                  type: "costmap_2d::StaticLayer"}
#   - {name: inflation,               type: "costmap_2d::InflationLayer"}

# static_map - True if using existing map

global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  transform_tolerance: 0.5
  static_map: True


