# local_costmap:
#   global_frame: odom
#   robot_base_frame: base_link
#   update_frequency: 2.0
#   publish_frequency: 2.0
#   transform_tolerance: 0.3 
#   static_map: false
#   rolling_window: true
#   width: 3.0
#   height: 3.0
#   resolution: 0.05

# local_costmap:
#   global_frame: odom
#   rolling_window: true

# global_frame: odom
# rolling_window: true

# plugins:
#   - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
#   - {name: inflation,                 type: "costmap_2d::InflationLayer"}

# # local_costmap:
# #   global_frame: odom
# #   robot_base_frame: base_link
# #   update_frequency: 2.0
# #   publish_frequency: 2.0
# #   transform_tolerance: 0.3 
# #   static_map: false
# #   rolling_window: true
# #   width: 3.0
# #   height: 3.0
# #   resolution: 0.05


local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 2.0
  transform_tolerance: 0.3 
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05